### PR TITLE
imaginator: allow resolv.conf to be injected and output from build.

### PR DESCRIPTION
**Pull request by rgooch**
If `/etc/resolv.conf` is in the `files` tree, it will override the host-provided one during the build.

If `/etc/resolv.conf` is in the `post-scripts-files` tree, it will be output in the image rather than being empty.

This fixes issue #44 and replaces PR #45.

### CODE REVIEW

**Comment by michaeljs1990** [comment]
Ah, sorry I have been MIA for a bit due to vacation. This is what my initial version of this looked like but I ran into issues because it required all the dependent images to configure the /etc/resolv.conf file as well.  I ended up with a solution that determined if resolv.conf was configured from the parent image and respects that parameter. https://github.com/michaeljs1990/Dominator-1/commits/mschuett/imaginator-fixes-for-uber

**Comment by rgooch** [comment]
Adding a new field to the image seems pretty hacky and covers just one use-case.

Taking a step back, it seems that what you're trying to do is impose a company-wide policy (in your case, your special `/etc/resolv.conf` file), correct? If so, how about a global configuration which allows you to inject files and run scripts for every image? I think that would be cleaner and more generally useful.

**Comment by michaeljs1990** [comment]
I agree that writing that code did feel pretty hacky :) Yes you are correct this is a company wide configuration that we want to enforce on everyone since they except to have access to these certain hosts and don't really think about DNS at all.

Global configuration for all images does sound desirable and I think would fix a few other issues for us as well that we currently use our base image for. How would a global configuration look in a build system like this? To me this sounds like some configurable directory you could tell imagination about and would apply at the end of every image.

Taking my approach and switching it to what you have here (plus a global config implementation) I think that would be placing our resolv.conf in both locations in that directory so all images at build and runtime have access to our DNS.

**Comment by rgooch** [comment]
One approach is to support a global almost-manifest directory which is merged with the manifest directory for the stream being built. This is the most powerful, but is the most prone to confusion, such as if a script is overridden. Also, the `package-list` file might not make sense to merge since you may have different base OSes (i.e. Debian vs. CentOS).

Another approach is to define multiple points in the manifest building process which apply the global policies (before package installs, before scripts, after scripts, etc.). It's also powerful, but it adds to the code and cognitive complexity.

A simple approach is to define a set of files to copy in and scrips to run _after_ the image stream manifest is processed. Anything you want to inject before a build you should be able to inherit from the `SourceImage`. For the special case of `/etc/resolv.conf` during the image build: I'd say that it's up to you to ensure that the build host has what you want.

**Comment by rgooch** [comment]
@michaeljs1990: what are your thoughts on which approach to take for a globally-imposed policy? My inclination is to take the simple approach (latter one in my previous comment).

**Pull request merged**
